version: "3"
services:
 local-mongo-user-preferences:
  image: mongo:4.2.5
  ports:
    - "27017:27017"
  environment:
    MONGO_INITDB_DATABASE: userPreferences
  volumes:
   - ./resources/database_entrypoint/mongodb:/docker-entrypoint-initdb.d
