version: "3"
services:
 mongo:
  container_name: mongo-user-preferences
  image: mongo:4.2.5
  ports:
    - "27018:27017"
  environment:
    MONGO_INITDB_DATABASE: userPreferences
  volumes:
   - ./resources/database_entrypoint/mongodb:/docker-entrypoint-initdb.d


# product-catalog:
#   container_name: product-catalog
#   image: product-catalog:latest
#   ports:
#     - "8080:8080"
#   environment:
#     ENVIRONMENT: PRD
#   depends_on:
#     - mongo
##     - redis
